# Generated by Django 4.1.7 on 2023-02-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_camping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camping',
            options={'ordering': ('-updated_dt',), 'verbose_name_plural': 'Camping'},
        ),
        migrations.RenameField(
            model_name='camping',
            old_name='created_at',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='camping',
            old_name='updated_at',
            new_name='updated_dt',
        ),
    ]
